[project]
name = "price-watcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ty-dwyer", email = "92275990+ty-dwyer@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.14.3",
    "beautifulsoup4>=4.15.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
price-watcher = "price_watcher:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
